# Generated by Django 4.2.5 on 2024-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='user', max_length=40)),
                ('lname', models.CharField(default='user', max_length=40)),
                ('mobileNo', models.CharField(default='user', max_length=20)),
                ('address', models.TextField(default=None)),
                ('email', models.EmailField(default=None, max_length=320)),
                ('country', models.CharField(default='India', max_length=10)),
                ('feedback', models.TextField(default=None)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
