# Generated by Django 4.2.5 on 2024-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_queries_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=40)),
                ('email', models.EmailField(default=None, max_length=320)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
