# Generated by Django 4.2.5 on 2024-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubishedbooks',
            name='BookImage',
            field=models.ImageField(default=None, null=True, upload_to='bookCover'),
        ),
    ]
