# Generated by Django 4.2.5 on 2024-03-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0004_alter_pubishedbooks_bookimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubishedbooks',
            name='BookImage',
        ),
    ]
