# Generated by Django 4.2.5 on 2024-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0005_remove_pubishedbooks_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubishedbooks',
            name='BookImage',
            field=models.FileField(default=None, null=True, upload_to='bookCover/'),
        ),
    ]
