# Generated by Django 4.2.5 on 2024-03-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0006_pubishedbooks_bookimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubishedbooks',
            old_name='Abstarct',
            new_name='Abstract',
        ),
    ]
