# Generated by Django 4.2.5 on 2024-03-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0008_rename_bookimage_pubishedbooks_bookfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubishRequestss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookFile', models.FileField(default=None, null=True, upload_to='bookCover/')),
                ('BookName', models.CharField(default='book', max_length=40)),
                ('Writername', models.CharField(default='user', max_length=500)),
            ],
        ),
    ]
