# Generated by Django 4.2.5 on 2024-03-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0009_pubishrequestss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PubishRequestss',
            new_name='PubishRequests',
        ),
    ]
