# Generated by Django 4.2.5 on 2024-03-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0011_alter_pubishedbooks_bookfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubishrequests',
            name='Message',
            field=models.TextField(default=None, null=True),
        ),
    ]
