# Generated by Django 4.2.5 on 2024-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0014_mailrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubishedbooks',
            old_name='Abstract',
            new_name='AboutAuthor',
        ),
        migrations.AddField(
            model_name='pubishedbooks',
            name='AboutBook',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pubishedbooks',
            name='BookFormat',
            field=models.CharField(default='paperback', max_length=500),
        ),
        migrations.AddField(
            model_name='pubishedbooks',
            name='Pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pubishedbooks',
            name='Writername',
            field=models.CharField(default='writer', max_length=500),
        ),
    ]
